version: '3'

services:
  quote-app-run:
    image: nandeshwar/quote
    container_name: quote
    build:
      context: ./
      dockerfile: "Dockerfile"
    ports:
      - "1922:1922"
    environment:
      - LOG_LEVEL=INFO
      - SERVER_RUN_DURATION_HOUR=12
      - DEVOTIONAL_IMAGE_MAX_SIZE=1200:900
      - HTTP_PORT=1922
      - SQLITE3_FILE=/db/quote.db

    volumes:
      - ./db:/db

    restart: always
